package:
  name: cpp-exceptions-test
  version: "0.1"
  _tag: pyodide.test
source:
  path: src
build:
  sharedlibrary: true
  script: |
    em++ -c throw.cpp -o throw.o ${SIDE_MODULE_CFLAGS} ${SIDE_MODULE_EXCEPTION_CFLAGS}
    em++ -c catch.cpp -o catch.o ${SIDE_MODULE_CFLAGS} ${SIDE_MODULE_EXCEPTION_CFLAGS}
    mkdir dist
    em++ throw.o ${SIDE_MODULE_LDFLAGS} -o dist/cpp-exceptions-test-throw.so ${SIDE_MODULE_EXCEPTION_LDFLAGS}
    em++ catch.o ${SIDE_MODULE_LDFLAGS} -o dist/cpp-exceptions-test-catch.so ${SIDE_MODULE_EXCEPTION_LDFLAGS}
